import { CONTROL_ACTIONS, KEY_NAMES } from '../input';

export const CONTROLLED_KEYS = {
  [CONTROL_ACTIONS.WALK_LEFT]: KEY_NAMES.a,
  [CONTROL_ACTIONS.WALK_RIGHT]: KEY_NAMES.d,
  [CONTROL_ACTIONS.WALK_UP]: KEY_NAMES.w,
  [CONTROL_ACTIONS.WALK_DOWN]: KEY_NAMES.s,
  [CONTROL_ACTIONS.SHOW_EXTERNAL]: KEY_NAMES.Space,
};

export const GAME_OPTIONS = {
  PIXEL_SCALE_NORMAL: 4,
  PIXEL_SCALE_RETINA: 3,
  DEBUG: true,
};

export const ENTITY_OPTIONS = {
  TILE_SIZE: 16,
  TILE_OFFSET_X: 24,
  TILE_OFFSET_Y: 32,
};
