import { CONTROL_ACTIONS, KEY_NAMES } from '../input';

export const CONTROLLED_KEYS = {
  [CONTROL_ACTIONS.WALK_LEFT]: KEY_NAMES.a,
  [CONTROL_ACTIONS.WALK_RIGHT]: KEY_NAMES.d,
  [CONTROL_ACTIONS.WALK_UP]: KEY_NAMES.w,
  [CONTROL_ACTIONS.WALK_DOWN]: KEY_NAMES.s,
  [CONTROL_ACTIONS.SHOW_EXTERNAL]: KEY_NAMES.Space,
};

export const GAME_OPTIONS = {
  GAME_PIXEL_SCALE: 2,
  BACKGROUND_COLOR: 0x160c21,
};
